### ISSUE TITLE
能否打一些 tag，以便 Bower 管理版本。

### ISSUE THREAD

**Issue by cssmagic** [fundon/bower-seajs#1]
很遗憾 Sea.js 官方没有提供 Bower 支持。不过这个项目也是个不错选择，谢谢 @fundon 。

Bower 会以 Git 源码库的 tag 来作为版本号，所以如果这个项目能给按照官方 release 来每个版本打 tag 就更好了。

**Comment by fundon** [comment]
已注销，被他人注册了。
